### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by dweldon** [shakee93/vue-toasted#102]
This is a really useful library, but I'm concerned that when I use a screen reader I don't hear any of the messages. At a minimum, would it be possible to render messages to a [live region](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions)?

**Comment by shakee93** [comment]
can i see an example where this is implemented ?

**Comment by dweldon** [comment]
There's a complete example in the linked [MDN article](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions), along with a [fiddle](https://jsfiddle.net/api/mdn/). The key section of the example is this:

```html
<div role="region" id="planetInfo" aria-live="polite">
  <h2 id="planetTitle">No planet selected</h2>
  <p id="planetDescription">Select a planet to view its description</p>
</div>
```

The trick is that the region has to exist on the page **before** it get's altered. So we'd need a live region that always exists to write to. I'd recommend the `visuallyhidden` class from [here](https://css-tricks.com/places-its-tempting-to-use-display-none-but-dont/):

```css
.visuallyhidden { 
  position: absolute; 
  overflow: hidden; 
  clip: rect(0 0 0 0); 
  height: 1px; width: 1px; 
  margin: -1px; padding: 0; border: 0; 
}
```

Finally, you can hear the results by installing a screen reader. If you are using chrome, you can try [ChromeVox](https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en). For a live region you shouldn't need to do anything other than enable the extension.
