### ISSUE TITLE
Multiline text is abnormal

### ISSUE THREAD

**Issue by Heathennn** [shakee93/vue-toasted#72]
if  the text is too long, margin(padding) top & bottom is almost 0, How do I rewrite its style ? please

**Comment by ad34** [comment]
I would like to display true multiline text as well, and for some reason if you use br tags, formatting is not correct.

**Comment by shakee93** [comment]
just add override the css. use below one for the primary style

```css
.toasted.primary {
    padding: 5px 20px;
}
```
